# Generated by Django 4.1 on 2022-08-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=255, verbose_name='Анонс')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('data', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
